### ISSUE TITLE
Suggestion: 𝓊𝓃𝒾𝒻𝓎 the new multiblock hatch overlays

### ISSUE THREAD

**Issue by loleq2105** [Puzzlebark/zedtech-gtce#1]
Apparently, the latest release of GTCE slaps those off-putting red arrows onto all fluid and item hatches. 
![2021-07-03_17 20 22](https://user-images.githubusercontent.com/52840858/124359201-39b48f80-dc24-11eb-935b-76a679817e9e.png)
Their textures appear to be located under `assets\gregtech\textures\blocks\overlay\machine`

**Comment by Puzzlebark** [comment]
This is resolved in the upcoming 0.6 release.
